
import './smallActions'
import './noPrefix'
import './actions/averageAudits'
import './actions/urban'
import './actions/define'
import './actions/imgur'
import './actions/currency'
import './actions/translator'
import './actions/help'
import './actions/dm'
import './actions/talk'
import './actions/google'
import './actions/gdef'
